# Generated by Django 5.1.4 on 2024-12-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("block_user", "Can block user")],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
