# Generated by Django 5.1.4 on 2024-12-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_alter_mailing_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="patronymic",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Отчество"),
        ),
    ]
