# Generated by Django 5.1.4 on 2024-12-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_client_patronymic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="patronymic",
            field=models.CharField(blank=True, default=1, max_length=30, verbose_name="Отчество"),
            preserve_default=False,
        ),
    ]
